language: node_js
node_js:
- "node"

before_script:
  - npm install

script:
  - npm run test -- --coverage

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token && echo COVERALLS_REPO_TOKEN && npm run coveralls
